// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANDGG58RkVdkAqJNcnrfPjs8o8C2VmmVQ',
    appId: '1:895028370656:web:02b4db6384c538ae5f8485',
    messagingSenderId: '895028370656',
    projectId: 'eshop-908d5',
    authDomain: 'eshop-908d5.firebaseapp.com',
    storageBucket: 'eshop-908d5.appspot.com',
    measurementId: 'G-FVHB7JBD50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY9digocRHvQEEoVpN6b3th9rJY_7kItw',
    appId: '1:895028370656:android:b9c3a4fe84b1b5475f8485',
    messagingSenderId: '895028370656',
    projectId: 'eshop-908d5',
    storageBucket: 'eshop-908d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAchaGeGq3XLvlfEyxx78qeeXw-X9Vwza8',
    appId: '1:895028370656:ios:7ed218ff7c4fc0995f8485',
    messagingSenderId: '895028370656',
    projectId: 'eshop-908d5',
    storageBucket: 'eshop-908d5.appspot.com',
    iosBundleId: 'com.example.bShopAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAchaGeGq3XLvlfEyxx78qeeXw-X9Vwza8',
    appId: '1:895028370656:ios:7ed218ff7c4fc0995f8485',
    messagingSenderId: '895028370656',
    projectId: 'eshop-908d5',
    storageBucket: 'eshop-908d5.appspot.com',
    iosBundleId: 'com.example.bShopAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANDGG58RkVdkAqJNcnrfPjs8o8C2VmmVQ',
    appId: '1:895028370656:web:c4c932ccedcb98395f8485',
    messagingSenderId: '895028370656',
    projectId: 'eshop-908d5',
    authDomain: 'eshop-908d5.firebaseapp.com',
    storageBucket: 'eshop-908d5.appspot.com',
    measurementId: 'G-765WQ8VTTX',
  );
}
